project:
  type: website

website:
  title: "Non Standard Dev"
  site-url: https://non-std-dev.netlify.app
  description: "Johnny Breen's blog."
  cookie-consent: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/johnnyb1694
      - icon: twitter
        href: https://twitter.com/johnnyb1694
      - icon: rss
        href: index.xml
format:
  html:
    theme: default
    css: styles.css

editor: visual

