project:
  type: website

website:
  title: "Non Standard Dev"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/johnnyb1694
      - icon: twitter
        href: https://twitter.com/johnnyb1694
format:
  html:
    theme: superhero
    css: styles.css

editor: visual

